### ISSUE TITLE
deploystation use case and outputs.conf

### ISSUE THREAD

**Issue by aamerik** [huit/puppet-splunk#54]
Hi, I have a splunk deploy station and would like to use this module to only install the UF and set the deploystation destination and admin pw.  However, it turns out this usecase also touched outputs.conf and puts in some entries with example.com in.  This is causing my splunk forwarder to enter a start/stop loop. 

```
class wrapper::splunk::forwarder (
  $type        = 'uf',
  $splunkadmin = ':admin:XXXXX:Administrator:admin:bar@foo.com::',
  $targeturi   = 'splunk-deploy.foo.co:8089',
  },
) {

  class { '::splunk':
    type        => $type,
    splunkadmin => $splunkadmin,
  }

  class { '::splunk::deploymentclient':
    targeturi => $targeturi,
  }

}
```

Resulting outputs.conf:

```
#### THIS FILE MANAGED BY PUPPET ####
[tcpout]
defaultGroup = example1,example2
disabled = false

[tcpout:example1]
server = server1.example.com:9997

[tcpout:example2]
server = server2.example.com:9997



#### THIS FILE MANAGED BY PUPPET ####
```

**Comment by aamerik** [comment]
I believe this line needs to be removed in the case of UF and LF

https://github.com/huit/puppet-splunk/blob/master/manifests/init.pp#L157

**Comment by aamerik** [comment]
@tfhartmann Do you know if Im using the module incorrectly? I'm trying to set up a UF and use my deploystation, which seems to be a supported configuration...however the module is creating an example options.conf and this is preventing the splunk UF from starting.

**Comment by tfhartmann** [comment]
@aamerik I think when we added the deployment server feature, we also assumed that you would want to pass parameters to set the outputs.conf as well.  I could remove that, or make outputs.conf management a true/false parameter, which would leave a UF that would need to be *totally* managed by a deployment server, is that more what your looking for?

**Comment by aamerik** [comment]
@thartmann yes, making outputs.conf management optional sounds like a great
solution here. Our UF refuses to start if an example outputs.conf is
created by the module. Thank you very much!

**Comment by aamerik** [comment]
@tfhartmann Did you have a chance to make outputs.conf file management optional in the case of UF?  Thank you very much

**Comment by tfhartmann** [comment]
@aamerik do you want to take a look at the above branch and see if thats what your looking for?

**Comment by tfhartmann** [comment]
@aamerik :+1: :-1:  ?

**Comment by aamerik** [comment]
@tfhartmann checking ;)

**Comment by aamerik** [comment]
@tfhartmann works for me sir! thank you very much!

**Comment by aamerik** [comment]
Would it be possible to request a new version posted to puppetforge?

**Comment by aamerik** [comment]
:thumbsup:

**Comment by tfhartmann** [comment]
All set, should now be released to the forge https://forge.puppetlabs.com/huit/splunk

**Comment by aamerik** [comment]
@tfhartmann I do not see "configure_outputs" param in master or v 1.7.0 tag.  Can you please clarify?
Thanks

**Comment by aamerik** [comment]
I dont think this was ever merged in from the feature branch above.
