### ISSUE TITLE
issue regarding tags.conf

### ISSUE THREAD

**Issue by dilipbailwal** [huit/puppet-splunk#57]
i have come across some errors regarding tags.conf file. in Splunk_TA_nix app.
Improper stanza [dhcpd_server_dhcprelease] in /opt/splunk/etc/apps/Splunk_TA_nix/default/tags.conf, line 38
it should be [eventype=dhcpd_server_dhcprelease]
and few more errors,
not sure what it is,
Value in stanza [app=/network/ntp:default] in /splunk_home/etc/apps/Splunk_TA_nix/default/tags.conf, line 783 not URI encoded: app = /network/ntp:default
                Value in stanza [shell=/bin/bash] in /splunk_home/etc/apps/Splunk_TA_nix/default/tags.conf, line 835 not URI encoded: shell = /bin/bash
                Value in stanza [shell=/bin/sh] in /splunk_home/etc/apps/Splunk_TA_nix/default/tags.conf, line 838 not URI encoded: shell = /bin/sh
                Value in stanza [shell=/usr/bin/bash] in /splunk_home/etc/apps/Splunk_TA_nix/default/tags.conf, line 841 not URI encoded: shell = /usr/bin/bash
                Value in stanza [shell=/usr/bin/pfksh] in /splunk_home/etc/apps/Splunk_TA_nix/default/tags.conf, line 844 not URI encoded: shell = /usr/bin/pfksh
                Value in stanza [shell=/usr/bin/pfsh] in /splunk_home/etc/apps/Splunk_TA_nix/default/tags.conf, line 847 not URI encoded: shell = /usr/bin/pfsh

please let me know fix for the above one..

**Comment by tfhartmann** [comment]
Released to the Forge
