### ISSUE TITLE
set value for maxKBps

### ISSUE THREAD

**Issue by SydOps** [huit/puppet-splunk#60]
Hi

I need set value for key `maxKBps` in limits.conf, but not sure how to update it via Hiera.

**Comment by tfhartmann** [comment]
At the moment this module doesn't manage the Splunk limits.conf, but it sounds like it's be a useful feature to add :)

**Comment by SydOps** [comment]
Thanks, waiting for the updates.

**Comment by SydOps** [comment]
@tfhartmann 

I have raised pull request #66  and add the feature to support `limits.conf`, I refer the code of `splunk::inputs` and hope I added and updated most related files.
