### ISSUE TITLE
change default setting "local" to others

### ISSUE THREAD

**Issue by SydOps** [huit/puppet-splunk#62]
After install splunk universal forwarder (agent) , the input and outputs are set to folder `/opt/splunkforwarder/etc/system/local`.

With which variable I can use to change to my defined folder? For example, set to 

    /opt/splunkforwarder/etc/system/ABC

**Comment by tfhartmann** [comment]
@SydOps in init.pp there is a parameter called [$splunkhome](https://github.com/huit/puppet-splunk/blob/master/manifests/init.pp)   $splunkhome/etc/system/local is the location that Splunk wants you to put local site-wide configs. If you want app specific config changes, you could deploy them in a Splunk App/TA which you could deploy either with this module or with a Deployment server. 

http://docs.splunk.com/Documentation/Splunk/6.2.5/Admin/Configurationfiledirectories

>$SPLUNK_HOME/etc/system/local
Local changes on a site-wide basis go here; for example, settings you want to make available to all apps. If the configuration file you're looking for doesn't already exist in this directory, create it and give it write permissions.

**Comment by SydOps** [comment]
Thanks, I am fine with this issue now.
