### ISSUE TITLE
Service is continuously set to enabled on system that use systemd

### ISSUE THREAD

**Issue by Renelast** [huit/puppet-splunk#80]
On CentOS 7 and RedHat 7 systems (and possibly others that use systemd) the splunk service is enabled on every puppetrun:

<code>Notice: /Stage[main]/Splunk::Service/Service[splunk]/enable: enable changed 'false' to 'true'</code>

This is probably because splunk still uses and "old-style" script in /etc/init.d that is not fully compatible with systemd. 

The service provider should be set to 'redhat' for these systems.

**Comment by nickperry** [comment]
In our fork of the puppetlabs-splunk module we fixed this as follows:

We let puppet choose the systemd provider and, critically, specify a restart method:
 

>  Service['splunk'] {
    restart  => '/opt/splunk/bin/splunk restart',
    start    => '/opt/splunk/bin/splunk start',
    status   => '/opt/splunk/bin/splunk status',
    stop     => '/opt/splunk/bin/splunk stop',
    pattern  => "splunkd -p ${splunkd_port} (restart|start)",
  }

  Service['splunkforwarder'] {
    restart => '/opt/splunkforwarder/bin/splunk restart',
    start   => '/opt/splunkforwarder/bin/splunk start',
    status  => '/opt/splunkforwarder/bin/splunk status',
    stop    => '/opt/splunkforwarder/bin/splunk stop',
  }


We drop unit files using file resources as follows:

        @file {'/usr/lib/systemd/system/splunk.service':
          ensure => present,
          owner  => root,
          group  => root,
          mode   => '0644',
          source => "puppet:///modules/${module_name}/splunk.service",
          tag    => 'splunk_server',
        }
        @file {'/usr/lib/systemd/system/splunkforwarder.service':
          ensure => present,
          owner  => root,
          group  => root,
          mode   => '0644',
          source => "puppet:///modules/${module_name}/splunkforwarder.service",
          tag    => 'splunk_forwarder',
        }

cat splunkforwarder.service

> [Unit]
Description=Splunk Forwarder
After=network.target
[Service]
RemainAfterExit=yes
ExecStart=/opt/splunkforwarder/bin/splunk start
ExecStop=/opt/splunkforwarder/bin/splunk stop
ExecReload=/opt/splunkforwarder/bin/splunk restart
[Install]
WantedBy=multi-user.target


cat splunk.service
>[Unit]
Description=Splunk
After=network.target
[Service]
RemainAfterExit=yes
ExecStart=/opt/splunk/bin/splunk start
ExecStop=/opt/splunk/bin/splunk stop
ExecReload=/opt/splunk/bin/splunk restart
[Install]
WantedBy=multi-user.target
