### ISSUE TITLE
Migrate module to voxpupuli

### ISSUE THREAD

**Issue by tfhartmann** [huit/puppet-splunk#83]
@huit/unix-linux-systems @huit/owners  Would anyone object to me migrating this module to voxpupuli?  This module has become pretty stagnant without anyone actually keeping it up. 

Info on migration can be found here 
https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli

**Comment by robruma** [comment]
@tfhartmann seems like a good option, been thinking about the same option for the IPA module, just need the time...

**Comment by tfhartmann** [comment]
LOL, yeah, thats actually where I got the idea from :p
